name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-workers:
    runs-on: ubuntu-latest
    name: Deploy Workers
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install

      - name: Publish Smart Tasks
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "smart_tasks"
          secrets: |
            PSCALE_HOST
            PSCALE_USER
            PSCALE_PASS
            BUCKET_LIMIT
            BUCKET_RECORD_LIMIT
        env:
          PSCALE_HOST: ${{ secrets.PSCALE_HOST }}
          PSCALE_USER: ${{ secrets.SMART_TASKS_PSCALE_USER }}
          PSCALE_PASS: ${{ secrets.SMART_TASKS_PSCALE_PASS }}
          BUCKET_LIMIT: ${{ secrets.SMART_TASKS_BUCKET_LIMIT }}
          BUCKET_RECORD_LIMIT: ${{ secrets.SMART_TASKS_BUCKET_RECORD_LIMIT }}

      - name: Publish Collections
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: "collections"
          secrets: |
            PSCALE_HOST
            PSCALE_USER
            PSCALE_PASS
            BUCKET_LIMIT
            BUCKET_RECORD_LIMIT
        env:
          PSCALE_HOST: ${{ secrets.PSCALE_HOST }}
          PSCALE_USER: ${{ secrets.COLLECTIONS_PSCALE_USER }}
          PSCALE_PASS: ${{ secrets.COLLECTIONS_PSCALE_PASS }}
          BUCKET_LIMIT: ${{ secrets.COLLECTIONS_BUCKET_LIMIT }}
          BUCKET_RECORD_LIMIT: ${{ secrets.COLLECTIONS_BUCKET_RECORD_LIMIT }}
