name: Create Database and Deploy Worker

on:
  workflow_dispatch:

env:
  pscale_base_directory: .pscale

jobs:
  db-worker:
    name: "Create Database and Deploy Worker - CLICK HERE"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install

      - name: Create database - please click on displayed link to authenticate
        timeout-minutes: 20
        env:
          ORG_NAME: ${{ github.event.inputs.pscale_org }}
          DB_NAME: ${{ github.event.inputs.service_name }}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: ./create-database.sh

      - name: Publish Cloud Clipboard Cloudflare Worker
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'account_id = ""'
          replace: ${{ format('account_id = "{0}"', github.event.inputs.cf_account_id) }}
          regex: false
          include: "cloud_clipboard/wrangler.toml"
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'name = "cloud_clipboard"'
          replace: ${{ format('name = "{0}"', github.event.inputs.service_name) }}
          regex: false
          include: "cloud_clipboard/wrangler.toml"
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ github.event.inputs.cf_api_token }}
          workingDirectory: "cloud_clipboard"
          secrets: |
            PSCALE_HOST
            PSCALE_USER
            PSCALE_PASS
        env:
          PSCALE_HOST: ${{ env.PSCALE_HOST }}
          PSCALE_USER: ${{ env.PSCALE_USER }}
          PSCALE_PASS: ${{ env.PSCALE_PASS }}
